#pragma once

#include <juce_audio_utils/juce_audio_utils.h>

// Thin MIDI-bridge processor. Audio passes through untouched; MIDI flows
// between the plugin host (or, in the Standalone app, real MIDI devices)
// and the TypeScript UI running in the WebView editor.
class MuseProcessor : public juce::AudioProcessor
{
public:
    MuseProcessor();

    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override {}
    bool isBusesLayoutSupported (const BusesLayout& layouts) const override;
    void processBlock (juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override                        { return true; }

    const juce::String getName() const override            { return "Moog Muse Interface"; }
    bool acceptsMidi() const override                      { return true; }
    bool producesMidi() const override                     { return true; }
    bool isMidiEffect() const override                     { return false; }
    double getTailLengthSeconds() const override           { return 0.0; }

    int getNumPrograms() override                          { return 1; }
    int getCurrentProgram() override                       { return 0; }
    void setCurrentProgram (int) override                  {}
    const juce::String getProgramName (int) override       { return {}; }
    void changeProgramName (int, const juce::String&) override {}

    void getStateInformation (juce::MemoryBlock&) override {}
    void setStateInformation (const void*, int) override   {}

    /** Called from the WebView (message thread): MIDI generated by the UI. */
    void queueMessageToHost (const juce::MidiMessage& message);

    /** Called from the editor timer: MIDI received from the host/devices. */
    std::vector<juce::MidiMessage> drainMessagesToUI();

private:
    juce::CriticalSection queueLock;
    std::vector<juce::MidiMessage> toHost, toUI;

    // In the Standalone app there is no host to route MIDI out, so we open a
    // hardware output directly (preferring a port whose name contains "Muse").
    std::unique_ptr<juce::MidiOutput> directOutput;
    bool triedDirectOutput = false;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MuseProcessor)
};
